# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nfs/stak/students/r/rindalp/bin/cmake

# The command to remove a file.
RM = /nfs/stak/students/r/rindalp/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/repo/batchDualEx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/repo/batchDualEx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/nfs/stak/students/r/rindalp/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nfs/stak/students/r/rindalp/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/nfs/stak/students/r/rindalp/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/nfs/stak/students/r/rindalp/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/nfs/stak/students/r/rindalp/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/nfs/stak/students/r/rindalp/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/repo/batchDualEx/CMakeFiles /scratch/repo/batchDualEx/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/repo/batchDualEx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named frontend.exe

# Build rule for target.
frontend.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frontend.exe
.PHONY : frontend.exe

# fast build rule for target.
frontend.exe/fast:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/build
.PHONY : frontend.exe/fast

#=============================================================================
# Target rules for targets named libBDX

# Build rule for target.
libBDX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libBDX
.PHONY : libBDX

# fast build rule for target.
libBDX/fast:
	$(MAKE) -f libBDX/CMakeFiles/libBDX.dir/build.make libBDX/CMakeFiles/libBDX.dir/build
.PHONY : libBDX/fast

#=============================================================================
# Target rules for targets named libBDXTests

# Build rule for target.
libBDXTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libBDXTests
.PHONY : libBDXTests

# fast build rule for target.
libBDXTests/fast:
	$(MAKE) -f libBDXTests/CMakeFiles/libBDXTests.dir/build.make libBDXTests/CMakeFiles/libBDXTests.dir/build
.PHONY : libBDXTests/fast

FrontEnd/Main.o: FrontEnd/Main.cpp.o

.PHONY : FrontEnd/Main.o

# target to build an object file
FrontEnd/Main.cpp.o:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/Main.cpp.o
.PHONY : FrontEnd/Main.cpp.o

FrontEnd/Main.i: FrontEnd/Main.cpp.i

.PHONY : FrontEnd/Main.i

# target to preprocess a source file
FrontEnd/Main.cpp.i:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/Main.cpp.i
.PHONY : FrontEnd/Main.cpp.i

FrontEnd/Main.s: FrontEnd/Main.cpp.s

.PHONY : FrontEnd/Main.s

# target to generate assembly for a file
FrontEnd/Main.cpp.s:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/Main.cpp.s
.PHONY : FrontEnd/Main.cpp.s

FrontEnd/UnitTests.o: FrontEnd/UnitTests.cpp.o

.PHONY : FrontEnd/UnitTests.o

# target to build an object file
FrontEnd/UnitTests.cpp.o:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/UnitTests.cpp.o
.PHONY : FrontEnd/UnitTests.cpp.o

FrontEnd/UnitTests.i: FrontEnd/UnitTests.cpp.i

.PHONY : FrontEnd/UnitTests.i

# target to preprocess a source file
FrontEnd/UnitTests.cpp.i:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/UnitTests.cpp.i
.PHONY : FrontEnd/UnitTests.cpp.i

FrontEnd/UnitTests.s: FrontEnd/UnitTests.cpp.s

.PHONY : FrontEnd/UnitTests.s

# target to generate assembly for a file
FrontEnd/UnitTests.cpp.s:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/UnitTests.cpp.s
.PHONY : FrontEnd/UnitTests.cpp.s

FrontEnd/ezOptionParser.o: FrontEnd/ezOptionParser.cpp.o

.PHONY : FrontEnd/ezOptionParser.o

# target to build an object file
FrontEnd/ezOptionParser.cpp.o:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/ezOptionParser.cpp.o
.PHONY : FrontEnd/ezOptionParser.cpp.o

FrontEnd/ezOptionParser.i: FrontEnd/ezOptionParser.cpp.i

.PHONY : FrontEnd/ezOptionParser.i

# target to preprocess a source file
FrontEnd/ezOptionParser.cpp.i:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/ezOptionParser.cpp.i
.PHONY : FrontEnd/ezOptionParser.cpp.i

FrontEnd/ezOptionParser.s: FrontEnd/ezOptionParser.cpp.s

.PHONY : FrontEnd/ezOptionParser.s

# target to generate assembly for a file
FrontEnd/ezOptionParser.cpp.s:
	$(MAKE) -f CMakeFiles/frontend.exe.dir/build.make CMakeFiles/frontend.exe.dir/FrontEnd/ezOptionParser.cpp.s
.PHONY : FrontEnd/ezOptionParser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... frontend.exe"
	@echo "... libBDX"
	@echo "... libBDXTests"
	@echo "... FrontEnd/Main.o"
	@echo "... FrontEnd/Main.i"
	@echo "... FrontEnd/Main.s"
	@echo "... FrontEnd/UnitTests.o"
	@echo "... FrontEnd/UnitTests.i"
	@echo "... FrontEnd/UnitTests.s"
	@echo "... FrontEnd/ezOptionParser.o"
	@echo "... FrontEnd/ezOptionParser.i"
	@echo "... FrontEnd/ezOptionParser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

